
meta:
  accessToken: EAACn32704NQBOyqzFGYdHKofE899wPOcx3euhZCfp6T31YNDKSf3Vgz0tNpnZBRygf6julZA1V8gT9cUlSwgOowHawqZAkQKtQkcAbcHQJZAMEyzQ8d1QYucblre1euvewvEV6mC0SNKj44zT0bpbIw7bKfQ133GTjE3m3qrWcW0wBdP9lEL5oi0YtZC7ZB0ANnEnrv0eZAPYSEZB4J5KqtXY7n0ZD
  appSecret: 496135f2ad82259aa52a6eb256b9d1fd
  accountId: 814227697103867
  productCatalog: 258227100404765
  appId: 184578081087700
  userAccessToken: EAACn32704NQBO4B8L7VZBgrjgRvOUCSrdZAT9D4BZCMDcCaIqBlWOX2jwq3PJwqZAuVPgAwMUboVRMc8IZCGoeXRL59dBSbQGUjImao4dCEUrKcOUud1FzSx8Cipc9by8PxlRNtig3KuV2tFkE1ZA6TWMt3eCTMrmDxHmx6zpzCZArQIMVC3C1fOZAgmNbdhEjXFBmmWMWnrjQ2jvefjy4Gt8DIQu2oZD

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/advert}
    username: ${DBUSER:postgres}
    password: ${POSTGRES_DB_PASSWORD:postgres@626}
  jpa:
    hibernate:
      ddl-auto: ${DB_INIT_DDL:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-zone: UTC